# Site settings
title: Adam Liska
email: ""
description: ""
baseurl: ""
url: "http://adliska.com"
twitter_username: adliska
github_username:  adliska

# Build settings
markdown: kramdown

collections:
 - news
